1. “The Indian zero stood for emptiness or absence, but also space, the firmament, the celestial vault, the atmosphere and ether, as well as nothing, the quantity not to be taken into account, the insignificant element.”
2. The early Indian symbols for the numerals 1 to 9.
3. “The dot on her forehead Increases her beauty tenfold, Just as a zero dot [sunya-bindu] Increases a number tenfold.”
4. Word Sanskrit Meaning
5. is true that as the empty voids and the dismal wilderness belong to zero, so the spirit of God and His light belong to the allpowerful One.” Gottfried Leibniz33
6. In French, the same ambiguities of meaning exist as in English. Originally, chiffre meant zero, but like cipher came to mean any of the numerals. The merger of the ideas for zero and Nothing gave rise to the name ‘null’ being used either to denote ‘Nothing’ or the circular symbol for zero. This meant a ‘figure of nothing’, or nulla figura in Latin. John of Hollywood (1256) writes in his Algorismus of the tenth digit that provides the zero symbol: “The tenth is called theca or circulus or figura nihili, because it stands for ‘nothing’. Yet when placed in its proper position, it gives value to the others.”47
7. “Among the great things which are found among us the existence of Nothing is the greatest.” Leonardo da Vinci1 “Nothing really matters.” Queen
8. Blaise Pascal’s famous confession that ‘The silence of infinite space terrifies me’. Nor
9. “the void exists … It is the void which keeps things distinct, being a kind of separation and division of things. This is true first and foremost of numbers; for the void keeps them distinct.”
10. “Humility collects the soul into a single point by the power of silence. A truly humble man has no desire to be known or ad-
11. mired by others, but wishes to form himself into himself, to become nothing, as if he had never been born. When he is completely hidden to himself in himself, he is completely with God.” Isaac of Ninevah (AD 600)25
12. This urge seems to be shared by human cultures the world over. Wherever anthropologists look they find elaborate decorations. Figure 2.3 Islamic decorations from (top) Badra in Azerbaijan, and (bottom) the Alhambra Palace in Granada, Spain.
13. “Miracles are explainable; it is the explanations that are miraculous.” Tim Robinson
14. “But if there is a void above and a void below, a void within and a void without, he who is intent on escaping void has need of a certain imaginative mobility.” Robert M. Adams30
15. Alongside these detailed arguments about the ways in which Nature staves off the creation of an intracosmic void, there were centuries of debate about the existence of an extracosmic void – a vacuum beyond the physical Universe. Aristotle considered the idea briefly but rejected it along with the whole idea of the plurality of worlds. His definition of a vacuum as that in which ‘the presence of a body is possible but not actual’ demanded such a conclusion. For ‘outside’ the Universe there is no possibility of body and hence no vacuum. In this respect, as we have seen, he is diametrically opposed to the Stoic view that there exists an infinite extracosmic void.
16. reductio ad absurdum.
17. “where Macbeth discovers that death is oblivion, Hamlet discovers that it is not. Macbeth discovers that, when death is oblivion, life is insignificant. Hamlet discovers that when one does not fear death, life with all its painful responsibilities can be borne and even borne nobly. In the end Hamlet knows for himself the relation between ‘to be’ and ‘not to be’ by which even his own death can affirm life.”55
18. René Descartes’ system of vortices (1636).7 Each vortex represents a solar system in a never-ending expanse of solar systems. The centres of the vortices (at the points marked S, E and A) are stars that are shining because of the turbulent motions of the vortices. The sinuous tube passing across the top of the picture is a comet that is moving too fast to be captured by any of the solar systems.
19. “If God had meant us to do philosophy he would have created us.” Marek Kohn20
20. “Now the sirens have a still more fatal weapon than their song, namely their silence … someone might possibly have escaped from their singing; but from their silence never.” Franz Kafka26
21. has been dubbed M theory.40
22. “The fool saith in his heart that there is no empty set. But if that were so, then the set of all such sets would be empty, and hence it would be the empty set.” Wesley Salmon
23. Now put inf in the right-hand slot and we have a peculiar definition for infinity minus 1, an infinite number less than infinity!,
24. “You know the formula: m over nought equals infinity, m being any positive number? Well, why not reduce the equation to a simpler form by multiplying both sides by nought? In which case, you have m equals infinity times nought. That is to say that a positive number is the product of zero and infinity. Doesn’t that demonstrate the creation of the universe by an infinite power out of nothing?” Aldous Huxley34
25. This is all very well, but having got a picture of how Einstein’s theory works by imagining that the presence of mass and energy creates curvatures in the geometry of space and changes in the rate of flow of time, shouldn’t empty universes all be flat? If they contain no stars, planets and atoms of matter, how can space be curved? What is there to do the curving?
26. The value of lambda required to keep the Universe static was very small, so small that its consequences on Earth would be far too small to have any perceptible effect on our measurements of gravity. This situation arose because the force increased with distance. It could be large over astronomical dimensions where it controlled the overall stability of the Universe, yet be very small over the small distances encountered on the surface of the Earth or in the solar system.
27. The simplest way to do this was suggested by the Dutch physicist Hendrik Casimir in 1948 and has been known ever since as the Casimir Effect. Figure 7.5 An undulating terrain displaying several local peaks and valleys.
28. “Thirty spokes share the wheel’s hub It is the centre hole that makes it useful. Shape clay into a vessel; It is the space within that makes it useful. Cut doors and windows for a room; It is the holes which make it useful. Therefore profit comes from what is there; Usefulness from what is not there.” Lao-tzu36
29. The fine structure constant tells the strength of the interaction that occurs when we fire two electrons towards each other. They have the same (negative) electric charge and so they repel one another like two magnetic North poles (see Figure 7.12).
30. This property, called ‘asymptotic freedom’ because it implies that if one continues to extrapolate to indefinitely increasing energies there would be no apparent interaction at all – the particles would be free – was predicted in 1973 and was quite unexpected.
31. This transition from a state where the minimum that the system resides in is symmetric about the zero value to one in which it is asymmetrical is a common phenomenon in Nature and it is called symmetry breaking.
32. Energy fields in the early Universe can behave like the pendulum. When the kinetic part of the energy is the largest, the field will change very quickly, but when the potential energy is largest it will change very slowly. Now suppose that the types of changes in the potential shape that we have just been looking at could come into play during the first moments of the Universe’s expansion. The scalar field could begin at high temperatures in a single stable vacuum state like that shown in Figure 8.5, but when the temperature falls below a particular value, Tc, a new vacuum state could appear at much lower energy.
33. In order for our Universe to be still within about twenty per cent of the critical rate after nearly fifteen billion years of expansion it must have begun expanding fantastically close to the critical divide.
34. Inflation grows a region bigger than the visible part of the Universe today from a region small enough to be coordinated by light signals near the beginning of the expansion. This offers an explanation for the uniformity of the visible Universe today.
35. Just as Heisenberg’s Uncertainty Principle forbids us from ever saying that a box is empty, so it forbids us from ever saying that the density or the temperature of the vacuum is perfectly smooth.
36. Universes with different numbers of dimensions of space and time have unusual properties that do not look conducive to complex information-processing and life except when there is one dimension of time and three large dimensions of space.16
37. “It has indeed been said that the highest praise of God consists in the denial of him by the atheist, who finds creation so perfect that it can dispense with a creator.” Marcel Proust1
38. Figure 9.1 The common patterns of cosmological traditions.
39. Basilides and his school in Antioch developed a Gnostic system unlike all others. It focused on the need to determine the nature of creation itself. Basilides proposed that in the beginning there was just pure ineffable Nothing.14 It may be that he equated Nothing with God, and on one occasion he describes God as ‘non-being’. This is probably just a rather extreme use of a form of negative theology in which one defines God in terms of the things that He is not.15 Unlike other Gnostics, Basilides rejects the idea that there is some germinating world-seed or pre-existent formless matter from which the world emerges. He regarded such devices as limitations on the power and superhuman nature of God. He rejects totally the idea that God works like a human craftsman or an artist using the materials that are at hand to fashion the Universe.
40. The interesting thing about the singularity that is predicted by these theorems is that there is no explanation as to why it occurs. It marks the edge of the Universe in time (see Figure 9.2). There is no before; no reason why the histories begin; no cause of the Universe. It is a description of a true creation out of nothing.
41. A curious postscript to the story of cyclic universes was recently discovered by Mariusz D browski and myself. We showed that if Einstein’s lambda force does exist then, no matter how small a positive value it takes, its repulsive gravitational effect will eventually cause the oscillations of a cyclic universe to cease.
42. Globally, the Universe may be self-reproducing but that will merely provide other expanding regions with new beginnings. Perhaps some of their inhabitants will master the techniques needed to initiate these local inflations to order and engineer their outcomes in life-enhancing ways. For us, there is a strange symmetry to existence. The Universe may once have appeared out of the quantum vacuum, retaining a little memory of its energy. Then in the far future that vacuum energy will reassert its presence and accelerate the expansion again, this time perhaps for ever. Globally, the self-reproduction may inspire new beginnings, new physics, new dimensions, but, along our world line, in our part of the Universe, there will ultimately be sameness, starless and lifeless, for ever, it seems. Perhaps it’s good that we won’t be there after all.
